deploy:
  app_path: /opt/react-sneakers/
  user: noteadmin
  password: noteadmin
user: ubuntu


sshpub_location: SSH_PUBKEY_HERE #the full path to your SSH public key ( e.g. /Users/username/.ssh/id_ed25519key-public )
root_pw: "hareon" #root password that should be set
user_name: admin #username for the created user
user_pw: "admin" #password for the new user
ssh_port: 22 #port number for ssh
